agents:
  host:
    llm: "openai/gpt-oss-20b"
    temperature: 0.0

  inventory:
    llm: "openai/gpt-oss-120b"
    temperature: 0.0
    agent_accuracy: "basic"
    agent_max_turns: 15
    agent_type: "mcp_tool_runner"
    agent_timeout: 120
    agent_total_timeout: 300
    agent_tools:
      - "splunk"

  query:
    llm: "openai/gpt-oss-120b"
    temperature: 0.4
    agent_accuracy: "standard"
    agent_max_turns: 20
    agent_type: "mcp_tool_runner"
    agent_timeout: 180
    agent_total_timeout: 900
    agent_tools:
      - "splunk"

  ticket:
    llm: "openai/gpt-oss-120b"
    temperature: 0.0
    agent_accuracy: "basic"
    agent_max_turns: 10
    agent_type: "mcp_tool_runner"
    agent_timeout: 60
    agent_total_timeout: 120
    agent_tools:
      - "jira"